- name: Install cli tools from repository
  become: yes
  package:
    name:
    - openssl
    - zip
    - unzip
    - expect
    - tree
    - ripgrep
    - tilix
    - task
    - ncdu
    - rsync
    - htop
    - make
    - ranger
    - xclip
    - wget
    - mtr
    - iftop
    - xmlstarlet
    - jq

- name: Install cli tools from repository (Ubuntu)
  become: yes
  package:
    name:
    - gdebi
    - openssh-server
    - dconf-cli
    - telnet
  when: ansible_distribution == "Ubuntu"

- name: Install cli tools from repository (Arch)
  become: yes
  pacman:
    name:
    - diff-so-fancy
    - openssh
    - dconf
    - inetutils
  when: ansible_distribution == "Archlinux"

- name: Install diff-so-fancy (Ubuntu)
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: /usr/local/bin/diff-so-fancy
    mode: 0755

- name: Install bat
  include: bat.yml

- name: Install gotop
  include: gotop.yml

- name: Install ctop
  include: ctop.yml

- name: Install cfssl
  include: cfssl.yml

- name: Install gopass
  include: gopass.yml

- name: Install vegeta
  include: vegeta.yml
